import {makeIcon} from './Icon';
import {IconComponents} from './sources';

export const Icons = {
  Arrow: makeIcon(IconComponents.Arrow, {width: 24, height: 24}),
  Logo: makeIcon(IconComponents.Logo, {width: 56, height: 56, viewBox: '0 0 56 56'}),
  LogoSmall: makeIcon(IconComponents.LogoSmall, {width: 24, height: 24}),
  Add: makeIcon(IconComponents.Add),
  Close: makeIcon(IconComponents.Close),
  CollectionSmall: makeIcon(IconComponents.CollectionStar, {
    width: 20,
    height: 20,
    viewBox: '0 0 24 24',
  }),
  Collection: makeIcon(IconComponents.CollectionStar, {width: 24, height: 24}),
  CategorySmall: makeIcon(IconComponents.CategoryFolder, {
    width: 20,
    height: 20,
    viewBox: '0 0 24 24',
  }),
  Category: makeIcon(IconComponents.CategoryFolder, {width: 24, height: 24}),
  SearchPanelSmall: makeIcon(IconComponents.Search, {
    width: 20,
    height: 20,
    viewBox: '0 0 24 24',
  }),
  Down: makeIcon(IconComponents.Down),
  Download: makeIcon(IconComponents.Download),
  Dribble: makeIcon(IconComponents.Dribble, {width: 20, height: 20, viewBox: '0 0 56 56'}),
  Lock: makeIcon(IconComponents.Lock, {width: 20, height: 20}),
  Search: makeIcon(IconComponents.Search, {width: 24, height: 24}),
  SearchSpinner: makeIcon(IconComponents.SearchSpinner, {width: 24, height: 24}),
  Cancel: makeIcon(IconComponents.Cancel, {width: 16, height: 16}),
  FacebookColor: makeIcon(IconComponents.FacebookColor),
  GitHubColor: makeIcon(IconComponents.GithubColor),
  GoogleColor: makeIcon(IconComponents.GoogleColor),
  LogoWithText: makeIcon(IconComponents.LogoWithText, {
    width: 230,
    height: 56,
    viewBox: '0 0 220 56',
  }),
  User: makeIcon(IconComponents.User, {width: 16, height: 16}),
  Menu: makeIcon(IconComponents.Menu),
  Facebook: makeIcon(IconComponents.Facebook, {viewBox: '2 2 20 20'}),
  Instagram: makeIcon(IconComponents.Instagram, {
    width: 20,
    height: 20,
    viewBox: '0 0 56 56',
  }),
  Twitter: makeIcon(IconComponents.Twitter, {viewBox: '2 2 20 20'}),
  Producthunt: makeIcon(IconComponents.ProductHunt, {viewBox: '2 2 20 20'}),
  Check: makeIcon(IconComponents.Check, {width: 10, height: 10, viewBox: '3 3 10 10'}),
  LogoText: makeIcon(IconComponents.LogoText, {
    width: 230,
    height: 56,
    viewBox: '0 0 230 56',
  }),
  Folder: makeIcon(IconComponents.Folder, {width: 26, height: 26}),
  IconLoader: makeIcon(IconComponents.IconLoader, {width: 24, height: 24}),
  Unlock: makeIcon(IconComponents.Unlock, {width: 48, height: 48}),
  Delete: makeIcon(IconComponents.Delete, {width: 16, height: 16}),
  Package: makeIcon(IconComponents.Package, {width: 22, height: 22}),
  BackArrow: makeIcon(IconComponents.Back, {width: 14, height: 13}),
  Filter: makeIcon(IconComponents.Filter, {width: 20, height: 20}),
};
