export const API_ENDPOINTS = Object.freeze({
  AUTH: '/auth',
  USERS: '/users',
  GET_USER: '/users/me',
  FORGOT_PASSWORD_REQUEST: '/users/reset-password-request',
  RESET_PASSWORD: '/users/reset-password',
  CATEGORIES: '/categories',
  DOWNLOAD_ACTION: '/downloadsactions',
  ICONS: '/icons',
  GET_ICONS_BY_CATEGORY: '/icons/icons-by-category',
  GET_ICON_FILE: '/downloads:iconId',
  GET_ICONS_FILES: '/downloads',
  GET_ICONS_FILES_BY_CATEGORY: '/downloads/download-icons-by-category',
  PACKS: '/packs',
  CANCEL_USER_SUBSCRIPTION: '/payments/cancel-subscription',
  PRICING: '/pricing',
  FEEDBACKS: '/feedbacks',
  FAQS: '/faqs',
});
